spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3306/carbontrust
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true


jwt:
  secret: carbontrust-super-secret-key-for-jwt-2026
  expiration: 3600000